hostname = "https://en.onepiece-cardgame.com"

[colors]
red = "Red"
green = "Green"
blue = "Blue"
purple = "Purple"
black = "Black"
yellow = "Yellow"

[attributes]
slash = "Slash"
strike = "Strike"
ranged = "Ranged"
special = "Special"
wisdom = "Wisdom"

[categories]
leader = "LEADER"
character = "CHARACTER"
event = "EVENT"
stage = "STAGE"
don = "DON"

[rarities]
common = "C"
uncommon = "UC"
rare = "R"
super_rare = "SR"
secret_rare = "SEC"
leader = "L"
special = "SP CARD"
treasure_rare = "TR"
promo = "P"
