hostname = "https://fr.onepiece-cardgame.com"

[colors]
red = "Rouge"
green = "Vert"
blue = "Bleu"
purple = "Violet"
black = "Noir"
yellow = "Jaune"

[attributes]
slash = "Tranche"
strike = "Frappe"
ranged = "Distance"
special = "Spécial"
wisdom = "Sagesse"
unknown = "?"

[categories]
leader = "LEADER"
character = "PERSONNAGE"
event = "ÉVÉNEMENTS"
stage = "LIEU"
don = "DON"

[rarities]
common = "C"
uncommon = "UC"
rare = "R"
super_rare = "SR"
secret_rare = "SEC"
leader = "L"
special = "SP CARD"
treasure_rare = "TR"
promo = "P"

[aliases]

[aliases.rarities]
special = [
    "SP",
    "SP CARD",
    "SEC SP",
    "SP SEC",
    "SR SP",
    "SP SR",
    "SP R",
    "R SP",
]
leader = [
    "L",
    " ",
] # blank rarity is used for ST13-001 Sabo leader card on the french site
